name: Build and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++

      - name: Build
        run: |
          g++ -std=c++17 -O2 ip_filter.cpp -o ip_filter
          chmod +x ip_filter

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ip_filter
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Автоматический токен
